runtime: nodejs20
env: standard

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 50

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  NODE_ENV: "production"
  # 如果您的应用使用其他环境变量，在这里添加它们

readiness_check:
  path: "/_ah/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/_ah/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

network:
  session_affinity: true

inbound_services:
- warmup

# 如果您使用 Cloud SQL，取消下面的注释并填入您的实例连接名
# beta_settings:
#   cloud_sql_instances: YOUR_INSTANCE_CONNECTION_NAME